import React from 'react';
import { Alert, Heading, Text } from '@puppet/react-components';
import './Home.scss';

const Home = () => (
  <div className="route-home">
    <Heading>Welcome to the Puppet Starter UI</Heading>
    <Alert>
      This application was generated by uikit from the Puppet Design System
    </Alert>
    <Text as="p">
      This application uses{' '}
      <a href="https://github.com/puppetlabs/design-system">
        puppetlabs/design-system
      </a>
      . Check out the README.md files in the design-system monorepo packages,
      browse the Styleguide and API documentation at{' '}
      <a href="https://puppetlabs.github.io/design-system">
        https://puppetlabs.github.io/design-system
      </a>
      , or reach out on Slack at{' '}
      <a href="https://puppet.slack.com/messages/CFFECRQAY">
        #team-design-system
      </a>{' '}
      or <a href="https://puppet.slack.com/messages/CF7H2EPLG">#aff-react</a>.
    </Text>
    <Text as="p">
      Next: Try running <code>uikit generate page MyPage</code> to create a new
      page with a corresponding route and link in the sidebar.
    </Text>
  </div>
);

export default Home;
