#!/bin/bash

set -e  # Exit if any command exits with a non-zero exit code

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $CURRENT_BRANCH == "master" ]];
then
  ./scripts/requireVersionBumps
fi

lerna run lint

if [[ -n $TRAVIS_PULL_REQUEST_BRANCH ]];
then
  lerna run test --since $TRAVIS_BRANCH
else
  lerna run test
fi
