#!/bin/bash

set -e  # Exit if any command exits with a non-zero exit code

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# If branch is master in CI or master locally
if [ "$TRAVIS_BRANCH" == "master" ] || [ "$CURRENT_BRANCH" == "master" ];
then
  # Require `lerna changed` to return 0 packages changed since last tagged release
  ./scripts/requireVersionBumps
fi

# If this is a pull request
if [ -n $TRAVIS_PULL_REQUEST_BRANCH ];
then
  # Only lint and test packages that have changed from the target branch
  lerna run test --since $TRAVIS_BRANCH
  lerna run lint --since $TRAVIS_BRANCH
else
  # Otherwise run lint and test in all packages
  lerna run test
  lerna run lint
fi
